name = "markdown-reader"
main = "worker.ts"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "app.prathamesh.cloud/mreader*", zone_name = "prathamesh.cloud" }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[[r2_buckets]]
binding = "PDF_BUCKET"
bucket_name = "markdown-reader-pdf-temp"

[vars]
PDF2MARKDOWN_API_URL = "https://pdf2html.templify.cloud"

[observability]
[observability.logs]
enabled = true
invocation_logs = true