name = "markdown-reader"
main = "worker.ts"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "app.prathamesh.cloud/mreader*", zone_name = "prathamesh.cloud" }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
[observability.logs]
enabled = true
invocation_logs = true